"""add stone margin

Revision ID: 0908f9b856de
Revises: bd90d6b0e906
Create Date: 2025-12-14 20:39:12.623074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0908f9b856de'
down_revision = 'bd90d6b0e906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stone_margin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('shopify_app', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('natural', 'lab', 'gemstones', name='stone_type'), nullable=False),
    sa.Column('unit', sa.Enum('carat', 'price', name='stone_unit'), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stone_margin_id'), 'stone_margin', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stone_margin_id'), table_name='stone_margin')
    op.drop_table('stone_margin')
    # ### end Alembic commands ###
