"""certificate No impliment

Revision ID: 0f2608ab2935
Revises: 600eb0baaa18
Create Date: 2025-12-17 01:25:23.562724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2608ab2935'
down_revision = '600eb0baaa18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'csv_diamonds', ['certificate_no'])
    op.create_unique_constraint(None, 'csv_gemstones', ['certificate_no'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'csv_gemstones', type_='unique')
    op.drop_constraint(None, 'csv_diamonds', type_='unique')
    # ### end Alembic commands ###
