"""your message

Revision ID: 107bd25c8314
Revises: 86be3c1ee23d
Create Date: 2025-12-10 21:03:36.212718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '107bd25c8314'
down_revision = '86be3c1ee23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csvdiamond', 'store_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('csvdiamond', 'shopify_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csvdiamond', 'shopify_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('csvdiamond', 'store_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
