"""group table create

Revision ID: 12fa503103d9
Revises: 41844d8605e4
Create Date: 2025-12-15 23:09:15.255320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12fa503103d9'
down_revision = '41844d8605e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=True),
    sa.Column('shopify_name', sa.String(length=100), nullable=True),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_store_id'), 'groups', ['store_id'], unique=False)
    op.create_table('group_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=True),
    sa.Column('shopify_name', sa.String(length=100), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('color_code', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_options_id'), 'group_options', ['id'], unique=False)
    op.create_index(op.f('ix_group_options_store_id'), 'group_options', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_options_store_id'), table_name='group_options')
    op.drop_index(op.f('ix_group_options_id'), table_name='group_options')
    op.drop_table('group_options')
    op.drop_index(op.f('ix_groups_store_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
