"""IngestionProcess change

Revision ID: 1e8037743ba1
Revises: b7e8a72f123b
Create Date: 2025-12-22 04:25:27.914554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e8037743ba1'
down_revision = 'b7e8a72f123b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestionprocess', sa.Column('process_sub_type', sa.String(length=50), nullable=True))
    op.add_column('ingestionprocess', sa.Column('store_id', sa.String(length=50), nullable=True))
    op.add_column('ingestionprocess', sa.Column('origin', sa.String(length=50), nullable=False))
    op.alter_column('ingestionprocess', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ingestionprocess', 'started_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('ingestionprocess', 'source_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestionprocess', sa.Column('source_name', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('ingestionprocess', 'started_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('ingestionprocess', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('ingestionprocess', 'origin')
    op.drop_column('ingestionprocess', 'store_id')
    op.drop_column('ingestionprocess', 'process_sub_type')
    # ### end Alembic commands ###
