"""Create StoreSetting table

Revision ID: 21ef6a6cd051
Revises: 9c5987d4f962
Create Date: 2025-12-16 23:26:58.930708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21ef6a6cd051'
down_revision = '9c5987d4f962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storesttings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('shopify_name', sa.String(length=255), nullable=False),
    sa.Column('custom_feed', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('feed_config', sa.JSON(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storesttings_id'), 'storesttings', ['id'], unique=False)
    op.alter_column('group_options', 'store_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'group_options', 'groups', ['group_id'], ['id'])
    op.alter_column('groups', 'store_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'store_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'group_options', type_='foreignkey')
    op.alter_column('group_options', 'store_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_storesttings_id'), table_name='storesttings')
    op.drop_table('storesttings')
    # ### end Alembic commands ###
