"""CSVGemstone table create

Revision ID: 2a0c32c8c93a
Revises: 7e1b5aaa978a
Create Date: 2025-12-12 02:35:05.656165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a0c32c8c93a'
down_revision = '7e1b5aaa978a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csv_gemstones', 'sub_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csv_gemstones', 'sub_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
