"""your message

Revision ID: 3164f073676f
Revises: b4e5bc9345bb
Create Date: 2026-01-15 22:10:02.221253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3164f073676f'
down_revision = 'b4e5bc9345bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stone_margin', 'shopify_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stone_margin', sa.Column('shopify_name', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
