"""your message

Revision ID: 40e85e635ce3
Revises: daa4c222de89
Create Date: 2025-12-10 21:26:26.641305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40e85e635ce3'
down_revision = 'daa4c222de89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_diamonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_no', sa.Integer(), nullable=False),
    sa.Column('lab', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=True),
    sa.Column('shopify_name', sa.String(length=100), nullable=True),
    sa.Column('carat', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('clarity', sa.String(length=20), nullable=False),
    sa.Column('cut', sa.String(length=20), nullable=False),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('certificate_no', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('image_source', sa.String(length=255), nullable=False),
    sa.Column('video_source', sa.String(length=255), nullable=False),
    sa.Column('is_available', sa.String(length=10), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('measurements', sa.String(length=50), nullable=False),
    sa.Column('polish', sa.String(length=20), nullable=False),
    sa.Column('symmetry', sa.String(length=20), nullable=False),
    sa.Column('fluorescence', sa.String(length=20), nullable=False),
    sa.Column('table', sa.Float(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.Column('girdle', sa.String(length=20), nullable=False),
    sa.Column('bgm', sa.String(length=50), nullable=False),
    sa.Column('treatment', sa.String(length=50), nullable=False),
    sa.Column('culet', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('csvdiamond')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csvdiamond',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('s_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lab', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('store_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('shopify_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('carat', mysql.FLOAT(), nullable=False),
    sa.Column('color', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('clarity', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('cut', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('shape', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('selling_price', mysql.FLOAT(), nullable=True),
    sa.Column('certificate_no', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('origin', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('image_source', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('video_source', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_available', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('vendor', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('measurements', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('polish', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('symmetry', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('fluorescence', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('table', mysql.FLOAT(), nullable=False),
    sa.Column('depth', mysql.FLOAT(), nullable=False),
    sa.Column('girdle', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('bgm', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('treatment', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('culet', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('modified_date', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('csv_diamonds')
    # ### end Alembic commands ###
