"""add stone margin

Revision ID: 41844d8605e4
Revises: 0908f9b856de
Create Date: 2025-12-14 20:50:20.268420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41844d8605e4'
down_revision = '0908f9b856de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stone_margin', sa.Column('shopify_name', sa.String(length=255), nullable=False))
    op.drop_column('stone_margin', 'shopify_app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stone_margin', sa.Column('shopify_app', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('stone_margin', 'shopify_name')
    # ### end Alembic commands ###
