"""Increase color length to 100

Revision ID: 4769805143c3
Revises: d6c5370485e9
Create Date: 2025-12-21 23:03:37.110582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4769805143c3'
down_revision = 'd6c5370485e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
