"""certificate No impliment

Revision ID: 5f06bdfbb3db
Revises: 0f2608ab2935
Create Date: 2025-12-17 03:36:37.620639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f06bdfbb3db'
down_revision = '0f2608ab2935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
