"""Create StoreSetting table

Revision ID: 600eb0baaa18
Revises: 21ef6a6cd051
Create Date: 2025-12-17 00:35:52.686949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '600eb0baaa18'
down_revision = '21ef6a6cd051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storesettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('shopify_name', sa.String(length=255), nullable=False),
    sa.Column('custom_feed', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('feed_config', sa.JSON(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storesettings_id'), 'storesettings', ['id'], unique=False)
    op.drop_index(op.f('ix_storesttings_id'), table_name='storesttings')
    op.drop_table('storesttings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storesttings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('shopify_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('custom_feed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('settings', mysql.JSON(), nullable=False),
    sa.Column('feed_config', mysql.JSON(), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('modified_date', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_storesttings_id'), 'storesttings', ['id'], unique=False)
    op.drop_index(op.f('ix_storesettings_id'), table_name='storesettings')
    op.drop_table('storesettings')
    # ### end Alembic commands ###
