"""your message

Revision ID: 74e2bd45f097
Revises: d26638a715aa
Create Date: 2026-03-16 01:54:30.031547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74e2bd45f097'
down_revision = 'd26638a715aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ring_data', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('ring_data', sa.Column('data', mysql.JSON(), nullable=False))
    op.drop_column('ring_data', 'image')
    op.drop_column('ring_data', 'metal_type')
    op.drop_column('ring_data', 'description')
    op.drop_column('ring_data', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ring_data', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.add_column('ring_data', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('ring_data', sa.Column('metal_type', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('ring_data', sa.Column('image', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('ring_data', 'data')
    op.drop_column('ring_data', 'title')
    # ### end Alembic commands ###
