"""CSVGemstone table create

Revision ID: 76eaff43f1c5
Revises: 2a0c32c8c93a
Create Date: 2025-12-12 02:37:44.184641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76eaff43f1c5'
down_revision = '2a0c32c8c93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csv_gemstones', 'video_source',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csv_gemstones', 'video_source',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
