"""your message

Revision ID: 7cc6636b2c41
Revises: 
Create Date: 2026-03-13 23:37:39.663016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc6636b2c41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_diamonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_no', sa.String(length=100), nullable=True),
    sa.Column('lab', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('shopify_name', sa.String(length=100), nullable=True),
    sa.Column('carat', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('clarity', sa.String(length=20), nullable=False),
    sa.Column('cut', sa.String(length=20), nullable=True),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('certificate_no', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image_source', sa.String(length=255), nullable=False),
    sa.Column('video_source', sa.String(length=255), nullable=False),
    sa.Column('is_available', sa.String(length=10), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('measurements', sa.String(length=50), nullable=True),
    sa.Column('polish', sa.String(length=20), nullable=True),
    sa.Column('symmetry', sa.String(length=20), nullable=True),
    sa.Column('fluorescence', sa.String(length=20), nullable=True),
    sa.Column('table', sa.Float(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.Column('girdle', sa.String(length=50), nullable=True),
    sa.Column('bgm', sa.String(length=50), nullable=True),
    sa.Column('treatment', sa.String(length=50), nullable=True),
    sa.Column('culet', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'certificate_no', name='uq_store_certificate')
    )
    op.create_table('csv_gemstones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_no', sa.String(length=100), nullable=True),
    sa.Column('lab', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('sub_type', sa.String(length=50), nullable=True),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('shopify_name', sa.String(length=100), nullable=True),
    sa.Column('carat', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('clarity', sa.String(length=20), nullable=False),
    sa.Column('cut', sa.String(length=20), nullable=True),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('certificate_no', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image_source', sa.String(length=255), nullable=False),
    sa.Column('video_source', sa.String(length=255), nullable=True),
    sa.Column('is_available', sa.String(length=10), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('measurements', sa.String(length=50), nullable=True),
    sa.Column('polish', sa.String(length=20), nullable=True),
    sa.Column('symmetry', sa.String(length=20), nullable=True),
    sa.Column('fluorescence', sa.String(length=20), nullable=True),
    sa.Column('table', sa.Float(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.Column('girdle', sa.String(length=100), nullable=True),
    sa.Column('bgm', sa.String(length=50), nullable=True),
    sa.Column('treatment', sa.String(length=50), nullable=True),
    sa.Column('culet', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'certificate_no', name='uq_store_certificate')
    )
    op.create_table('diamondpricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diamond_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('base_price', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('selling_price', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diamondpricing_id'), 'diamondpricing', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('shopify_name', sa.String(length=100), nullable=True),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_store_id'), 'groups', ['store_id'], unique=False)
    op.create_table('ingesteddiamonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_diamond_id', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_stock_id', sa.String(length=100), nullable=True),
    sa.Column('lab', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('natural', 'lab', 'gemstones', name='stone_type'), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=True),
    sa.Column('carat', sa.Float(), nullable=False),
    sa.Column('color', sa.Enum('D', 'E', 'F', 'G', 'H', 'I', 'J', name='diamond_color'), nullable=False),
    sa.Column('clarity', sa.Enum('FL', 'IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2', 'I1', 'I2', 'I3', name='diamond_clarity'), nullable=False),
    sa.Column('cut', sa.String(length=50), nullable=True),
    sa.Column('shape', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('certificate_no', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image_source', sa.String(length=255), nullable=True),
    sa.Column('video_source', sa.String(length=255), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('mesurements', sa.String(length=100), nullable=True),
    sa.Column('polish', sa.String(length=50), nullable=True),
    sa.Column('symmetry', sa.String(length=50), nullable=True),
    sa.Column('fluorescence', sa.String(length=50), nullable=True),
    sa.Column('table', sa.String(length=20), nullable=True),
    sa.Column('depth', sa.String(length=20), nullable=True),
    sa.Column('girdle', sa.String(length=50), nullable=True),
    sa.Column('bgm', sa.String(length=50), nullable=True),
    sa.Column('treatment', sa.String(length=50), nullable=True),
    sa.Column('culet', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingesteddiamonds_id'), 'ingesteddiamonds', ['id'], unique=False)
    op.create_table('ingestionprocess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('processed_items', sa.Integer(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('process_sub_type', sa.String(length=50), nullable=True),
    sa.Column('store_id', sa.String(length=50), nullable=True),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestionprocess_id'), 'ingestionprocess', ['id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('store_id', sa.String(length=100), nullable=False),
    sa.Column('shopify_app', sa.String(length=255), nullable=True),
    sa.Column('order_name', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('currency_code', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('order_notes', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=True),
    sa.Column('app_used', sa.Boolean(), nullable=True),
    sa.Column('referring_site', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('diamonds_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ringdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metal_type', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stone_margin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('natural', 'lab', 'gemstones', name='stone_type'), nullable=False),
    sa.Column('unit', sa.Enum('carat', 'price', name='stone_unit'), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stone_margin_id'), 'stone_margin', ['id'], unique=False)
    op.create_table('storesettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('shopify_name', sa.String(length=255), nullable=True),
    sa.Column('custom_feed', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('feed_config', sa.JSON(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storesettings_id'), 'storesettings', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('group_options',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('shopify_name', sa.String(length=100), nullable=True),
    sa.Column('group_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('color_code', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_options_id'), 'group_options', ['id'], unique=False)
    op.create_index(op.f('ix_group_options_store_id'), 'group_options', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_options_store_id'), table_name='group_options')
    op.drop_index(op.f('ix_group_options_id'), table_name='group_options')
    op.drop_table('group_options')
    op.drop_table('user')
    op.drop_index(op.f('ix_storesettings_id'), table_name='storesettings')
    op.drop_table('storesettings')
    op.drop_index(op.f('ix_stone_margin_id'), table_name='stone_margin')
    op.drop_table('stone_margin')
    op.drop_table('ringdata')
    op.drop_table('order')
    op.drop_index(op.f('ix_ingestionprocess_id'), table_name='ingestionprocess')
    op.drop_table('ingestionprocess')
    op.drop_index(op.f('ix_ingesteddiamonds_id'), table_name='ingesteddiamonds')
    op.drop_table('ingesteddiamonds')
    op.drop_index(op.f('ix_groups_store_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_diamondpricing_id'), table_name='diamondpricing')
    op.drop_table('diamondpricing')
    op.drop_table('csv_gemstones')
    op.drop_table('csv_diamonds')
    # ### end Alembic commands ###
