"""your message

Revision ID: 7ddadd495274
Revises: 9346293f7756
Create Date: 2025-12-10 22:35:59.178519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ddadd495274'
down_revision = '9346293f7756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csv_diamonds', 's_no',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csv_diamonds', 's_no',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
