"""CSVGemstone table create

Revision ID: 7e1b5aaa978a
Revises: 7ddadd495274
Create Date: 2025-12-12 01:54:00.024898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1b5aaa978a'
down_revision = '7ddadd495274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_gemstones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_no', sa.String(length=100), nullable=True),
    sa.Column('lab', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('sub_type', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=True),
    sa.Column('shopify_name', sa.String(length=100), nullable=True),
    sa.Column('carat', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('clarity', sa.String(length=20), nullable=False),
    sa.Column('cut', sa.String(length=20), nullable=True),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('certificate_no', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image_source', sa.String(length=255), nullable=False),
    sa.Column('video_source', sa.String(length=255), nullable=False),
    sa.Column('is_available', sa.String(length=10), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('measurements', sa.String(length=50), nullable=True),
    sa.Column('polish', sa.String(length=20), nullable=True),
    sa.Column('symmetry', sa.String(length=20), nullable=True),
    sa.Column('fluorescence', sa.String(length=20), nullable=True),
    sa.Column('table', sa.Float(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.Column('girdle', sa.String(length=20), nullable=True),
    sa.Column('bgm', sa.String(length=50), nullable=True),
    sa.Column('treatment', sa.String(length=50), nullable=True),
    sa.Column('culet', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('csv_gemstones')
    # ### end Alembic commands ###
