"""your message

Revision ID: 805badc6bc17
Revises: 0c51cc98fa35
Create Date: 2025-12-24 01:58:00.007046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805badc6bc17'
down_revision = '0c51cc98fa35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diamondpricing', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('diamondpricing', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diamondpricing', 'updated_at')
    op.drop_column('diamondpricing', 'created_at')
    # ### end Alembic commands ###
