"""your message

Revision ID: 86be3c1ee23d
Revises: 6590a93a0297
Create Date: 2025-12-10 04:45:16.156566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86be3c1ee23d'
down_revision = '6590a93a0297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
