"""certificate No impliment

Revision ID: 898482eca888
Revises: 5f06bdfbb3db
Create Date: 2025-12-17 03:45:15.274504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898482eca888'
down_revision = '5f06bdfbb3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('certificate_no'), table_name='csv_diamonds')
    op.drop_index(op.f('certificate_no'), table_name='csv_gemstones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('certificate_no'), 'csv_gemstones', ['certificate_no'], unique=True)
    op.create_index(op.f('certificate_no'), 'csv_diamonds', ['certificate_no'], unique=True)
    # ### end Alembic commands ###
