"""your message

Revision ID: 9346293f7756
Revises: 40e85e635ce3
Create Date: 2025-12-10 21:31:08.431082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9346293f7756'
down_revision = '40e85e635ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csv_diamonds', 'cut',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('csv_diamonds', 'origin',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('csv_diamonds', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('csv_diamonds', 'measurements',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('csv_diamonds', 'polish',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('csv_diamonds', 'symmetry',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('csv_diamonds', 'fluorescence',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('csv_diamonds', 'girdle',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('csv_diamonds', 'bgm',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('csv_diamonds', 'treatment',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('csv_diamonds', 'culet',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('csv_diamonds', 'location',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csv_diamonds', 'location',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('csv_diamonds', 'culet',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('csv_diamonds', 'treatment',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('csv_diamonds', 'bgm',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('csv_diamonds', 'girdle',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('csv_diamonds', 'fluorescence',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('csv_diamonds', 'symmetry',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('csv_diamonds', 'polish',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('csv_diamonds', 'measurements',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('csv_diamonds', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('csv_diamonds', 'origin',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('csv_diamonds', 'cut',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
