"""order table create

Revision ID: b4e5bc9345bb
Revises: cf581caa795b
Create Date: 2025-12-30 22:18:03.486016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4e5bc9345bb'
down_revision = 'cf581caa795b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'order_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('order', 'store_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('order', 'shopify_app',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('order', 'order_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('order', 'order_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('order', 'total_amount',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('order_id'), table_name='order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('order_id'), 'order', ['order_id'], unique=True)
    op.alter_column('order', 'total_amount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('order', 'order_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('order', 'order_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('order', 'shopify_app',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('order', 'store_id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('order', 'order_id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
