"""your migration message

Revision ID: c1193324a81b
Revises: 4769805143c3
Create Date: 2025-12-22 01:17:02.459976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1193324a81b'
down_revision = '4769805143c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingesteddiamonds', 'created_at',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('ingesteddiamonds', 'updated_at',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingesteddiamonds', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('ingesteddiamonds', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
