"""your migration message

Revision ID: c353adbb7744
Revises: c1193324a81b
Create Date: 2025-12-22 01:38:19.578631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c353adbb7744'
down_revision = 'c1193324a81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingesteddiamonds', 'carat',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ingesteddiamonds', 'price',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ingesteddiamonds', 'is_available',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingesteddiamonds', 'is_available',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('ingesteddiamonds', 'price',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('ingesteddiamonds', 'carat',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
