"""order table create

Revision ID: cf581caa795b
Revises: 805badc6bc17
Create Date: 2025-12-30 22:16:20.360148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf581caa795b'
down_revision = '805badc6bc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('shopify_app', sa.String(length=100), nullable=False),
    sa.Column('order_name', sa.String(length=100), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('currency_code', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('order_notes', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=True),
    sa.Column('app_used', sa.Boolean(), nullable=True),
    sa.Column('referring_site', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('diamonds_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
