"""your message

Revision ID: d33a5f87aa30
Revises: 1e8037743ba1
Create Date: 2025-12-23 00:04:41.548000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33a5f87aa30'
down_revision = '1e8037743ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diamondpricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diamond_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('base_price', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('selling_price', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diamondpricing_id'), 'diamondpricing', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diamondpricing_id'), table_name='diamondpricing')
    op.drop_table('diamondpricing')
    # ### end Alembic commands ###
