"""ingested_diamonds table

Revision ID: d6c5370485e9
Revises: 9cd0b5784f90
Create Date: 2025-12-21 22:08:27.760317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6c5370485e9'
down_revision = '9cd0b5784f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingesteddiamonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_diamond_id', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_stock_id', sa.String(length=100), nullable=True),
    sa.Column('lab', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('natural', 'lab', 'gemstones', name='stone_type'), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=True),
    sa.Column('carat', sa.String(length=20), nullable=False),
    sa.Column('color', sa.Enum('D', 'E', 'F', 'G', 'H', 'I', 'J', name='diamond_color'), nullable=False),
    sa.Column('clarity', sa.Enum('FL', 'IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2', 'I1', 'I2', 'I3', name='diamond_clarity'), nullable=False),
    sa.Column('cut', sa.String(length=50), nullable=True),
    sa.Column('shape', sa.String(length=50), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.Column('certificate_no', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image_source', sa.String(length=255), nullable=True),
    sa.Column('video_source', sa.String(length=255), nullable=True),
    sa.Column('is_available', sa.String(length=10), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('mesurements', sa.String(length=100), nullable=True),
    sa.Column('polish', sa.String(length=50), nullable=True),
    sa.Column('symmetry', sa.String(length=50), nullable=True),
    sa.Column('fluorescence', sa.String(length=50), nullable=True),
    sa.Column('table', sa.String(length=20), nullable=True),
    sa.Column('depth', sa.String(length=20), nullable=True),
    sa.Column('girdle', sa.String(length=50), nullable=True),
    sa.Column('bgm', sa.String(length=50), nullable=True),
    sa.Column('treatment', sa.String(length=50), nullable=True),
    sa.Column('culet', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingesteddiamonds_id'), 'ingesteddiamonds', ['id'], unique=False)
    op.alter_column('csv_diamonds', 'store_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint('uq_store_certificate', 'csv_diamonds', ['store_id', 'certificate_no'])
    op.alter_column('csv_gemstones', 'store_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('csv_gemstones', 'color',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=10),
               nullable=False)
    op.create_unique_constraint('uq_store_certificate', 'csv_gemstones', ['store_id', 'certificate_no'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_store_certificate', 'csv_gemstones', type_='unique')
    op.alter_column('csv_gemstones', 'color',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('csv_gemstones', 'store_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('uq_store_certificate', 'csv_diamonds', type_='unique')
    op.alter_column('csv_diamonds', 'store_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_ingesteddiamonds_id'), table_name='ingesteddiamonds')
    op.drop_table('ingesteddiamonds')
    # ### end Alembic commands ###
