"""your message

Revision ID: daa4c222de89
Revises: 107bd25c8314
Create Date: 2025-12-10 21:07:08.834292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'daa4c222de89'
down_revision = '107bd25c8314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csvdiamond', 'selling_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csvdiamond', 'selling_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
