from sqlalchemy import Column, Integer, String, Enum, DateTime, Float, Boolean
from core.enums import StoneType, Color, Clarity
from db.base_class import Base
    
class IngestedDiamonds(Base):
    id = Column(Integer, primary_key=True, index=True)
    source_diamond_id = Column(String(50), nullable=False)
    source_name = Column(String(100), nullable=False)
    source_stock_id = Column(String(100), nullable=True)
    lab = Column(String(50), nullable=True)
    type = Column(Enum(StoneType, name="stone_type"), nullable=False)
    store_id = Column(String(50), nullable=True)
    carat = Column(Float, nullable=False)
    color = Column(Enum(Color, name="diamond_color"), nullable=False)
    clarity = Column(Enum(Clarity, name="diamond_clarity"), nullable=False)
    cut = Column(String(50), nullable=True)
    shape = Column(String(50), nullable=False)
    price = Column(Float, nullable=False)
    certificate_no = Column(String(100), nullable=True)
    origin = Column(String(100), nullable=True)
    description = Column(String(255), nullable=True)
    image_source = Column(String(255), nullable=True)
    video_source = Column(String(255), nullable=True)
    is_available = Column(Boolean, nullable=True)
    vendor = Column(String(100), nullable=True)
    mesurements = Column(String(100), nullable=True)
    polish = Column(String(50), nullable=True)
    symmetry = Column(String(50), nullable=True)
    fluorescence = Column(String(50), nullable=True)
    table = Column(String(20), nullable=True)
    depth = Column(String(20), nullable=True)
    girdle = Column(String(50), nullable=True)
    bgm = Column(String(50), nullable=True)
    treatment = Column(String(50), nullable=True)
    culet = Column(String(50), nullable=True)
    location = Column(String(100), nullable=True)
    created_at = Column(DateTime, nullable=False)
    updated_at = Column(DateTime, nullable=False)
